name: 02 - Eventos
on: 
    pull_request:
    workflow_dispatch:
    schedule:
    - cron: "15 4,5 * * *"

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: ShowTrigger
              run: |
                echo "Event name: ${{ github.event_name }}"

